pom.xml

Signed-off-by: nickboldt...
add missing vars
Signed-off-by: nickboldt <nboldt@redhat.com>

add missing vars

---

plugins/com.redhat.fabric8analytics.lsp.eclipse/src/com/redhat/fabric8analytics/lsp/eclipse/ExitHandler.java
plugins/com.redhat.fabric8analytics.lsp.eclipse/src/com/redhat/fabric8analytics/lsp/eclipse/Fabric8AnalyticsStreamConnectionProvider.java
plugins/com.redhat.fabric8analytics.lsp.eclipse/src/com/redhat/fabric8analytics/lsp/eclipse/TokenCheck.java
plugins/com.redhat.fabric8analytics.lsp.eclipse/src/com/redhat/fabric8analytics/lsp/eclipse/Utils.java

Signed-off-by: Jeff MAURY <jmaury@redhat.com>
Got it working, request was send to API but stack analyses window keep displaying 'Loading'

Add integration to OSIO login plugin

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.core/META-INF/MANIFEST.MF
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/Fabric8AnalysisLSCoreActivator.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/RecommenderAPIException.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/RecommenderAPIProvider.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/internal/Utils.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/ExitHandler.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/Fabric8AnalysisLSUIActivator.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/WorkerThread.java

The communication with server was performed on several places acros UI plugin. A new class RecommenderAPIProvider.java was created in core plugin to encapsulate the communication. Improved error handling.

Extracted communication with server to one class

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/RecommenderAPIProvider.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/WorkspaceFilesFinder.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/plugin.xml
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/ExitHandler.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/WorkerThread.java

- the behaviour changed so that only selected projects are processed
- only the root pom.xml files can be analyzed
- the Stack analyzes menu is displayed only for projects and pom.xml files

Refactoring of finding the pom.xml files

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.core/.gitignore
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/RecommenderAPIProvider.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/.gitignore
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/build.properties
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/pom.xml
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/Fabric8AnalyticsStreamConnectionProvider.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/WorkerThread.java

Changed server directory and updated the official lsp server repository.

Change server dir

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/WorkspaceFilesFinder.java

Covers case when project is not accessible.

Updated lookup of maven pom files.

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/RecommenderAPIProvider.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/Fabric8AnalysisLSUIActivator.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/Fabric8AnalyticsStreamConnectionProvider.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/StackAnalysesView.java

This should work also with paths that contains spaces.

Changed the lookup of server's location

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/META-INF/MANIFEST.MF
pom.xml

- added repository to pom.xml
- changed version of parent pom file
- added dependency to openshift.io plugin to manifest file

Updated project's build

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.core/META-INF/MANIFEST.MF
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/Fabric8AnalysisLSCoreActivator.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/internal/Utils.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/ExitHandler.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/WorkspaceFilesFinder.java

Decoupling core plugin from all ui references

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/RecommenderAPIProvider.java

Changed URL for retrieving analyses.

---

pom.xml
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.itests/META-INF/MANIFEST.MF
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.itests/build.properties
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.itests/pom.xml
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.itests/resources/maven-project-test/pom.xml
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.itests/resources/maven-project-test/src/.gitignore
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.itests/src/com/redhat/fabric8analytics/lsp/eclipse/ui/itests/SmokeSuite.java
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.itests/src/com/redhat/fabric8analytics/lsp/eclipse/ui/itests/StackAnalysesContextMenuItemTests.java
tests/pom.xml

Squashed commits from branch initTest_2
[Jenkins run](https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fabric8-analytics.itests/20/)

Tests structure initialization with sample itest

---

tests/com.redhat.fabric8analytics.lsp.eclipse.ui.itests/src/com/redhat/fabric8analytics/lsp/eclipse/ui/itests/SmokeSuite.java
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.itests/src/com/redhat/fabric8analytics/lsp/eclipse/ui/itests/StackAnalysesContextMenuItemTests.java

Added copyrights to test and test suite

Added copyrights to tests

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/RecommenderAPIProvider.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/META-INF/MANIFEST.MF
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/plugin.properties
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/plugin.xml
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/scripts/lsp-server.sh
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/AuthorizeHandler.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/ExitHandler.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/Fabric8AnalysisPreferencePage.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/Fabric8AnalyticsStreamConnectionProvider.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/internal/Fabric8AnalysisPreferences.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/internal/ThreeScaleIntegration.java

WIP: 3scale integration and associated work

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/META-INF/MANIFEST.MF
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/internal/WorkspaceFilesFinder.java
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/META-INF/MANIFEST.MF
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/build.properties
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/pom.xml
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/src/com/redhat/fabric8analytics/lsp/eclipse/ui/tests/WorkspaceFilesFinderTest.java
tests/pom.xml

Created test for WrokspaceFilesFinder. The test for recursive search has not been implemented yet since it would be failing.

Added test for WorkspaceFilesFinder.

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/META-INF/MANIFEST.MF
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/Fabric8AnalyticsStreamConnectionProvider.java
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/META-INF/MANIFEST.MF
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/src/com/redhat/fabric8analytics/lsp/eclipse/ui/tests/Fabric8AnalyticsStreamConnectionProviderTest.java

Junit for Fabric8AnalyticsStreamConnectionProvider

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/pom.xml

Download LSP server during generate-sources phase

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/EditorComposite.java

Get Pom file from current editor instead of current selection

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/EditorComposite.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/ExitHandler.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/internal/AnalysesJobHandler.java

Remove static references to editor composite

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.core/META-INF/MANIFEST.MF
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/Fabric8AnalysisLSCoreActivator.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/RecommenderAPIProvider.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/internal/PomContentBody.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/job/RetrieveResultsJob.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/job/SendToFabric8AnalysisJob.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/EditorComposite.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/ExitHandler.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/internal/AnalysesJobHandler.java

1. job takes care of sending effective pom files to Fabric8Analytics
2. job retrieves the results, if the results are not ready, reschedule in 5 seconds.
We try 5 times, then fail.

Create 2 jobs where:

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/RecommenderAPIProvider.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/Fabric8AnalyticsStreamConnectionProvider.java
pom.xml
tests/com.redhat.fabric8analytics.lsp.eclipse.core.tests/src/com/redhat/fabric8analytics/lsp/eclipse/core/tests/RecommenderAPIProviderTest.java
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.itests/pom.xml
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/META-INF/MANIFEST.MF
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/pom.xml
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/resources/securepass
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/src/com/redhat/fabric8analytics/lsp/eclipse/ui/tests/Fabric8AnalyticsStreamConnectionProviderTest.java
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/src/com/redhat/fabric8analytics/lsp/eclipse/ui/tests/Fabric8AnalyticsStreamConnectionProviderWrapper.java
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/src/com/redhat/fabric8analytics/lsp/eclipse/ui/tests/WorkspaceFilesFinderTest.java
tests/pom.xml

Reenable tests

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/RecommenderAPIProvider.java
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/internal/ThreeScaleIntegration.java

Remove System.out.println calls

---

README.adoc
features/com.redhat.fabric8analytics.lsp.eclipse.feature/feature.properties
features/com.redhat.fabric8analytics.lsp.eclipse.feature/feature.xml
features/com.redhat.fabric8analytics.lsp.eclipse.feature/pom.xml
features/pom.xml
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/META-INF/MANIFEST.MF
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/plugin.properties
plugins/com.redhat.fabric8analytics.lsp.eclipse.core/pom.xml
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/META-INF/MANIFEST.MF
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/plugin.properties
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/plugin.xml
plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/pom.xml
plugins/pom.xml
pom.xml
site/category.xml
site/pom.xml
tests/com.redhat.fabric8analytics.lsp.eclipse.core.tests/META-INF/MANIFEST.MF
tests/com.redhat.fabric8analytics.lsp.eclipse.core.tests/pom.xml
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/META-INF/MANIFEST.MF
tests/com.redhat.fabric8analytics.lsp.eclipse.ui.tests/pom.xml
tests/pom.xml

bump version to 0.0.3 since new name = new version
Signed-off-by: nickboldt <nboldt@redhat.com>

rename plugin, feature, ui components, update site to Dependency Analytics

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/pom.xml

Signed Off by: Geetika Batra <gbatra@redhat.com>

Updated ca lsp server download file.

---

pom.xml

- Remove references to JBoss Tools P2 repositories
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

JBIDE-26709: remove openshift.io bundles

---

plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/Fabric8AnalyticsStreamConnectionProvider.java
tests/com.redhat.fabric8analytics.lsp.eclipse.core.tests/src/com/redhat/fabric8analytics/lsp/eclipse/core/tests/RecommenderAPIProviderTest.java
tests/com.redhat.fabric8analytics.lsp.eclipse.core.tests/src/com/redhat/fabric8analytics/lsp/eclipse/core/tests/ThreeScaleAPIProviderTest.java

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

JBIDE-26914: update unit tests according removal of openshift.io

---

.github/workflows/build_test.yml
pom.xml

Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

JBIDE-28184: Update PR workflows to test against Java 17
